name: Payment Service

on:
  push:
    paths: ['payment-service/**']
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest -f Dockerfile ./payment-service
        docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest