name: Product Service

on:
  push:
    paths: ['product-service/**']
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      run: |
        DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker-compose build product-service
        docker tag ${{ secrets.DOCKER_USERNAME }}/product-service:latest ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest