name: User Service

on:
  push:
    paths: ['user-service/**']
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest -f Dockerfile ./user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest